/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Aug 28 14:20:51 2025


#include "IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT, "yarp.device.IsaacSimMultipleAnalogSensorsNWCROS2")
}


IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser()
{
}


std::vector<std::string> IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("ft_topic_names");
    params.push_back("imu_topic_names");
    return params;
}


bool IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="ft_topic_names")
    {
        return false;
    }
    if (paramName =="imu_topic_names")
    {
        return false;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter ft_topic_names
    {
        if (config.check("ft_topic_names"))
        {
            {
                m_ft_topic_names.clear();
                yarp::os::Bottle* tempBot = config.find("ft_topic_names").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_ft_topic_names.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) <<"parameter 'ft_topic_names' is not a properly formatted bottle";
                }
            }
            yCInfo(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Parameter 'ft_topic_names' using value:" << m_ft_topic_names;
        }
        else
        {
            yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'ft_topic_names' not found!";
            yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the FT topics to connect";
            return false;
        }
        prop_check.unput("ft_topic_names");
    }

    //Parser of parameter imu_topic_names
    {
        if (config.check("imu_topic_names"))
        {
            {
                m_imu_topic_names.clear();
                yarp::os::Bottle* tempBot = config.find("imu_topic_names").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_imu_topic_names.push_back(tempBot->get(i).asString());
                    }
                }
                else
                {
                     yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) <<"parameter 'imu_topic_names' is not a properly formatted bottle";
                }
            }
            yCInfo(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Parameter 'imu_topic_names' using value:" << m_imu_topic_names;
        }
        else
        {
            yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'imu_topic_names' not found!";
            yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the IMU topics to connect";
            return false;
        }
        prop_check.unput("imu_topic_names");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(IsaacSimMultipleAnalogSensorsNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: IsaacSimMultipleAnalogSensorsNWCROS2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': Set the name for ROS node\n");
    doc = doc + std::string("'ft_topic_names': Specify the name of the FT topics to connect\n");
    doc = doc + std::string("'imu_topic_names': Specify the name of the IMU topics to connect\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device IsaacSimMultipleAnalogSensorsNWCROS2 --node_name MASBridgeSubscriber --ft_topic_names <mandatory_value> --imu_topic_names <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device IsaacSimMultipleAnalogSensorsNWCROS2 --ft_topic_names <mandatory_value> --imu_topic_names <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
