/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Aug 28 14:20:51 2025


#ifndef ISAACSIMMULTIPLEANALOGSENSORSNWCROS2_PARAMSPARSER_H
#define ISAACSIMMULTIPLEANALOGSENSORSNWCROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class IsaacSimMultipleAnalogSensorsNWCROS2.
*
* These are the used parameters:
* | Group name | Parameter name  | Type           | Units | Default Value       | Required | Description                                   | Notes                                      |
* |:----------:|:---------------:|:--------------:|:-----:|:-------------------:|:--------:|:---------------------------------------------:|:------------------------------------------:|
* | -          | node_name       | string         | -     | MASBridgeSubscriber | 0        | Set the name for ROS node                     | must not start with a leading '/'          |
* | -          | ft_topic_names  | vector<string> | -     | -                   | 1        | Specify the name of the FT topics to connect  | Each element must start with a leading '/' |
* | -          | imu_topic_names | vector<string> | -     | -                   | 1        | Specify the name of the IMU topics to connect | Each element must start with a leading '/' |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device IsaacSimMultipleAnalogSensorsNWCROS2 --node_name MASBridgeSubscriber --ft_topic_names <mandatory_value> --imu_topic_names <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device IsaacSimMultipleAnalogSensorsNWCROS2 --ft_topic_names <mandatory_value> --imu_topic_names <mandatory_value>
* \endcode
*
*/

class IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser();
    ~IsaacSimMultipleAnalogSensorsNWCROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"IsaacSimMultipleAnalogSensorsNWCROS2"};
    const std::string m_device_name = {"IsaacSimMultipleAnalogSensorsNWCROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_node_name_defaultValue = {"MASBridgeSubscriber"};
    const std::string m_ft_topic_names_defaultValue = {""};
    const std::string m_imu_topic_names_defaultValue = {""};

    std::string m_node_name = {"MASBridgeSubscriber"};
    std::vector<std::string> m_ft_topic_names = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::vector<std::string> m_imu_topic_names = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
