/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Aug 28 16:58:25 2025


#ifndef ISAACSIMCLOCKROS2_PARAMSPARSER_H
#define ISAACSIMCLOCKROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class IsaacSimClockROS2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                            | Notes                             |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:--------------------------------------:|:---------------------------------:|
* | -          | node_name      | string | -     | ClockSubYarp  | 0        | Set the name for ROS node              | must not start with a leading '/' |
* | -          | topic_name     | string | -     | /clock        | 0        | Specify the name of ROS2 clock topic   | must start with a leading '/'     |
* | -          | port_name      | string | -     | /clock        | 0        | Specify the name of clock port to open | must start with a leading '/'     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device IsaacSimClockROS2 --node_name ClockSubYarp --topic_name /clock --port_name /clock
* \endcode
*
* \code{.unparsed}
* yarpdev --device IsaacSimClockROS2
* \endcode
*
*/

class IsaacSimClockROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    IsaacSimClockROS2_ParamsParser();
    ~IsaacSimClockROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"IsaacSimClockROS2"};
    const std::string m_device_name = {"IsaacSimClockROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_node_name_defaultValue = {"ClockSubYarp"};
    const std::string m_topic_name_defaultValue = {"/clock"};
    const std::string m_port_name_defaultValue = {"/clock"};

    std::string m_node_name = {"ClockSubYarp"};
    std::string m_topic_name = {"/clock"};
    std::string m_port_name = {"/clock"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
