/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Thu Aug 28 16:58:25 2025


#include "IsaacSimClockROS2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(IsaacSimClockROS2ParamsCOMPONENT, "yarp.device.IsaacSimClockROS2")
}


IsaacSimClockROS2_ParamsParser::IsaacSimClockROS2_ParamsParser()
{
}


std::vector<std::string> IsaacSimClockROS2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("topic_name");
    params.push_back("port_name");
    return params;
}


bool IsaacSimClockROS2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="topic_name")
    {
        paramValue = m_topic_name;
        return true;
    }
    if (paramName =="port_name")
    {
        paramValue = m_port_name;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string IsaacSimClockROS2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      IsaacSimClockROS2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter topic_name
    {
        if (config.check("topic_name"))
        {
            m_topic_name = config.find("topic_name").asString();
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'topic_name' using value:" << m_topic_name;
        }
        else
        {
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'topic_name' using DEFAULT value:" << m_topic_name;
        }
        prop_check.unput("topic_name");
    }

    //Parser of parameter port_name
    {
        if (config.check("port_name"))
        {
            m_port_name = config.find("port_name").asString();
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'port_name' using value:" << m_port_name;
        }
        else
        {
            yCInfo(IsaacSimClockROS2ParamsCOMPONENT) << "Parameter 'port_name' using DEFAULT value:" << m_port_name;
        }
        prop_check.unput("port_name");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(IsaacSimClockROS2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(IsaacSimClockROS2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      IsaacSimClockROS2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: IsaacSimClockROS2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': Set the name for ROS node\n");
    doc = doc + std::string("'topic_name': Specify the name of ROS2 clock topic\n");
    doc = doc + std::string("'port_name': Specify the name of clock port to open\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device IsaacSimClockROS2 --node_name ClockSubYarp --topic_name /clock --port_name /clock\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device IsaacSimClockROS2\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
