/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Sep 26 11:45:26 2025


#include "IsaacSimControlBoardNWCROS2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(IsaacSimControlBoardNWCROS2ParamsCOMPONENT, "yarp.device.IsaacSimControlBoardNWCROS2")
}


IsaacSimControlBoardNWCROS2_ParamsParser::IsaacSimControlBoardNWCROS2_ParamsParser()
{
}


std::vector<std::string> IsaacSimControlBoardNWCROS2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("joint_state_topic_name");
    params.push_back("motor_state_topic_name");
    params.push_back("joint_references_topic_name");
    return params;
}


bool IsaacSimControlBoardNWCROS2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="joint_state_topic_name")
    {
        paramValue = m_joint_state_topic_name;
        return true;
    }
    if (paramName =="motor_state_topic_name")
    {
        paramValue = m_motor_state_topic_name;
        return true;
    }
    if (paramName =="joint_references_topic_name")
    {
        paramValue = m_joint_references_topic_name;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string IsaacSimControlBoardNWCROS2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      IsaacSimControlBoardNWCROS2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter joint_state_topic_name
    {
        if (config.check("joint_state_topic_name"))
        {
            m_joint_state_topic_name = config.find("joint_state_topic_name").asString();
            yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Parameter 'joint_state_topic_name' using value:" << m_joint_state_topic_name;
        }
        else
        {
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'joint_state_topic_name' not found!";
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the joint state topic to connect";
            return false;
        }
        prop_check.unput("joint_state_topic_name");
    }

    //Parser of parameter motor_state_topic_name
    {
        if (config.check("motor_state_topic_name"))
        {
            m_motor_state_topic_name = config.find("motor_state_topic_name").asString();
            yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Parameter 'motor_state_topic_name' using value:" << m_motor_state_topic_name;
        }
        else
        {
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'motor_state_topic_name' not found!";
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the motor state topic to connect";
            return false;
        }
        prop_check.unput("motor_state_topic_name");
    }

    //Parser of parameter joint_references_topic_name
    {
        if (config.check("joint_references_topic_name"))
        {
            m_joint_references_topic_name = config.find("joint_references_topic_name").asString();
            yCInfo(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Parameter 'joint_references_topic_name' using value:" << m_joint_references_topic_name;
        }
        else
        {
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'joint_references_topic_name' not found!";
            yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the FT topic to open to publish the joint references";
            return false;
        }
        prop_check.unput("joint_references_topic_name");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(IsaacSimControlBoardNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      IsaacSimControlBoardNWCROS2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: IsaacSimControlBoardNWCROS2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': Set the name for ROS node\n");
    doc = doc + std::string("'joint_state_topic_name': Specify the name of the joint state topic to connect\n");
    doc = doc + std::string("'motor_state_topic_name': Specify the name of the motor state topic to connect\n");
    doc = doc + std::string("'joint_references_topic_name': Specify the name of the FT topic to open to publish the joint references\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device IsaacSimControlBoardNWCROS2 --node_name ControlBoardBridgeSubscriber --joint_state_topic_name <mandatory_value> --motor_state_topic_name <mandatory_value> --joint_references_topic_name <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device IsaacSimControlBoardNWCROS2 --joint_state_topic_name <mandatory_value> --motor_state_topic_name <mandatory_value> --joint_references_topic_name <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
