/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Jul  7 12:05:20 2025


#ifndef ISAACSIMRGBDSENSORNWCROS2_PARAMSPARSER_H
#define ISAACSIMRGBDSENSORNWCROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class IsaacSimRGBDSensorNWCROS2.
*
* These are the used parameters:
* | Group name | Parameter name   | Type   | Units | Default Value        | Required | Description                                          | Notes                             |
* |:----------:|:----------------:|:------:|:-----:|:--------------------:|:--------:|:----------------------------------------------------:|:---------------------------------:|
* | -          | node_name        | string | -     | RGBDBridgeSubscriber | 0        | Set the name for ROS node                            | must not start with a leading '/' |
* | -          | rgb_topic_name   | string | -     | -                    | 1        | Specify the name of the RGB topic to connect         | must start with a leading '/'     |
* | -          | depth_topic_name | string | -     | -                    | 1        | Specify the name of the depth image topic to connect | must start with a leading '/'     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device IsaacSimRGBDSensorNWCROS2 --node_name RGBDBridgeSubscriber --rgb_topic_name <mandatory_value> --depth_topic_name <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device IsaacSimRGBDSensorNWCROS2 --rgb_topic_name <mandatory_value> --depth_topic_name <mandatory_value>
* \endcode
*
*/

class IsaacSimRGBDSensorNWCROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    IsaacSimRGBDSensorNWCROS2_ParamsParser();
    ~IsaacSimRGBDSensorNWCROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"IsaacSimRGBDSensorNWCROS2"};
    const std::string m_device_name = {"IsaacSimRGBDSensorNWCROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_node_name_defaultValue = {"RGBDBridgeSubscriber"};
    const std::string m_rgb_topic_name_defaultValue = {""};
    const std::string m_depth_topic_name_defaultValue = {""};

    std::string m_node_name = {"RGBDBridgeSubscriber"};
    std::string m_rgb_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    std::string m_depth_topic_name = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
