/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Aug  4 16:09:37 2025


#include "IsaacSimRGBDSensorNWCROS2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT, "yarp.device.IsaacSimRGBDSensorNWCROS2")
}


IsaacSimRGBDSensorNWCROS2_ParamsParser::IsaacSimRGBDSensorNWCROS2_ParamsParser()
{
}


std::vector<std::string> IsaacSimRGBDSensorNWCROS2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("node_name");
    params.push_back("rgb_topic_name");
    params.push_back("depth_topic_name");
    return params;
}


bool IsaacSimRGBDSensorNWCROS2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="node_name")
    {
        paramValue = m_node_name;
        return true;
    }
    if (paramName =="rgb_topic_name")
    {
        paramValue = m_rgb_topic_name;
        return true;
    }
    if (paramName =="depth_topic_name")
    {
        paramValue = m_depth_topic_name;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string IsaacSimRGBDSensorNWCROS2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      IsaacSimRGBDSensorNWCROS2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter node_name
    {
        if (config.check("node_name"))
        {
            m_node_name = config.find("node_name").asString();
            yCInfo(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using value:" << m_node_name;
        }
        else
        {
            yCInfo(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Parameter 'node_name' using DEFAULT value:" << m_node_name;
        }
        prop_check.unput("node_name");
    }

    //Parser of parameter rgb_topic_name
    {
        if (config.check("rgb_topic_name"))
        {
            m_rgb_topic_name = config.find("rgb_topic_name").asString();
            yCInfo(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Parameter 'rgb_topic_name' using value:" << m_rgb_topic_name;
        }
        else
        {
            yCError(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'rgb_topic_name' not found!";
            yCError(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the RGB topic to connect";
            return false;
        }
        prop_check.unput("rgb_topic_name");
    }

    //Parser of parameter depth_topic_name
    {
        if (config.check("depth_topic_name"))
        {
            m_depth_topic_name = config.find("depth_topic_name").asString();
            yCInfo(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Parameter 'depth_topic_name' using value:" << m_depth_topic_name;
        }
        else
        {
            yCError(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Mandatory parameter 'depth_topic_name' not found!";
            yCError(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "Description of the parameter: Specify the name of the depth image topic to connect";
            return false;
        }
        prop_check.unput("depth_topic_name");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(IsaacSimRGBDSensorNWCROS2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      IsaacSimRGBDSensorNWCROS2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: IsaacSimRGBDSensorNWCROS2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'node_name': Set the name for ROS node\n");
    doc = doc + std::string("'rgb_topic_name': Specify the name of the RGB topic to connect\n");
    doc = doc + std::string("'depth_topic_name': Specify the name of the depth image topic to connect\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device IsaacSimRGBDSensorNWCROS2 --node_name RGBDBridgeSubscriber --rgb_topic_name <mandatory_value> --depth_topic_name <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device IsaacSimRGBDSensorNWCROS2 --rgb_topic_name <mandatory_value> --depth_topic_name <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
